[project]
name = "ais-dev2il-wine-quality"
version = "0.1.0"
description = "The final project to prepare for the exam."
readme = "README.md"
requires-python = ">=3.13"
# the Python modules used in the project has to be listed here
dependencies = [
    "numpy>=1.24.0",
    "pandas==2.2.3",
    "pyarrow==19.0.1",
    "fastparquet==2024.11.0",
    "scikit-learn>=1.8.0",
    "mlflow>=2.0.0",
    "optuna>=3.0.0",
    "dagshub>=0.3.0",
    "requests>=2.31.0",
    "fastapi>=0.110.0",
    "uvicorn>=0.28.0",
    "pydantic>=2.6.0"
]

[dependency-groups]
dev = [
    "dvc[s3]>=3.67.1",
]